var mongoose = require('mongoose');
var Schema = mongoose.Schema;

var schemaV = new Schema({

    barcodeNumber: {type: String },
    batchId: {type: String },
    dispatchStatus: {type: String },
    date: {type: String },
    countSize:{type:Number},
    preRefNumber: {type: String },
    refNumReceive: {type: String },
    refCases: {type: Number },
    aggCases: {type: Number },
    pallet: {type: Number },
    name: {type: String, },
    casesReceived: {type: Number},
    cases: {type: Number},
    count: {type: Number,},
    mformat: {type: String},
    status: {type: String,},
    status2: {type: String},

    statusCheck: {type: String},
    statusCheck2: {type: String},
    pallets: {type: Number },
    prPallet: {type: Number },
    countPallet: {type: Number },
    currentPallet: {type: Number },
    remainderCases: {type: Number },
    warehouse: {type: String},
    shift: {type: String},
    availableCases: {type: Number},
    dateValue: {type: Number},
    receiver: {type: String},
    type: {type: String},
    month: {type: String},
    year: {type: String},
    category: { type: String},
    subCategory: { type: String},
    lot:{type:Number},
    refNumber:{type:String},
    location:{type:String},
    expiryDate: {type: String },
    mformat: {type: String },
    expiryDateValue: {type: String },
    expiryMformat: {type: String },
    casesDispatched: {type: Number },
    casesRemaining: {type: Number },
    availableCasesDispatch: {type: Number },
    timeOfDispatch: {type: String },
    dateValueDispatch: {type: Number },
    truck: {type: String },
    type: {type: String },
    reason: {type: String },
    mformatDispatch: {type: String },
    salesPerson: {type: String },
    dispatcher: {type: String },
    casesBatch: {type: Number },
    casesBatchR: {type: Number },
    palletCasesBatch:{type:Number},
    casesBatchNumber: {type: Number },
    refNumDispatch: {type: String },
    size: {type: Number },
    nSize2: {type: Number },
    sizeR: {type: Number },
    position:{type:String},
    itemPos:{type:String},
    replacedBarcode:{type:String},
    returnsType:{type:String},
    dispatchValue: {type: Number },
    fifoPosition: {type: Number },
    palletDispatched: {type: Number },
    palletRcvd: {type: Number },
    prRefNumber: {type: String },
    prPallet: {type: Number },
    palletRemaining: {type: Number },
    replacementCase: {type: Number },
    batchPallets:{type:Number},
    palletCount:{type:Number},
 
   
   
});

module.exports = mongoose.model('StockV', schemaV);